#Run report and save in C drive 
$filename = "ErrorReport" + (Get-Date -Format "MM-dd-yyyy")
Get-EventLog -LogName System -EntryType Error -Newest 5 | ConvertTo-Html -Title "Windows Errors" -Body (Get-Date) -PreContent "<P> Generated by Crisanta E. Jaggers" -PostContent "For more details check the full server log" | Out-File -filepath C:\DailyErrorReports\$filename.html